<?php
defined('is_running') or die('Not an entry point...');
$fileVersion = '4.3.4';
$fileModTime = '1411088316';
$file_stats = array (
  'created' => 1388501802,
  'gpversion' => '4.3.4',
  'modified' => 1411088316,
  'username' => 'Snotling',
);

$meta_data = array (
  'file_number' => 26,
  'file_type' => 'text',
);

$file_sections = array (
  0 => 
  array (
    'type' => 'text',
    'content' => '<h2>Web Sites</h2>

<p>From around the known world, here are a few:</p>

<p><strong>Strike-To-Stun</strong><br />
<a border="0" href="http://forum.strike-to-stun.net"><img alt="Generated by WebThumbnail.org" src="http://api.webthumbnail.org?width=200&amp;height=200&amp;screen=1024&amp;url=http://forum.strike-to-stun.net" /></a></p>

<p><strong>Winds of Chaos</strong><br />
<a border="0" href="http://www.windsofchaos.com"><img alt="Generated by WebThumbnail.org" src="http://api.webthumbnail.org?width=200&amp;height=200&amp;screen=1024&amp;url=www.windsofchaos.com" /></a></p>

<p><strong>Mad Alfred</strong><br />
<a border="0" href="http://www.madalfred.com"><img alt="Generated by WebThumbnail.org" src="http://api.webthumbnail.org?width=200&amp;height=200&amp;screen=1024&amp;url=http://www.madalfred.com/" /></a></p>

<p><strong>Silverghost - PC Generation</strong><br />
<a border="0" href="http://silverghost.dyndns.org/wfrp/"><img alt="Generated by WebThumbnail.org" src="http://api.webthumbnail.org?width=200&amp;height=200&amp;screen=1024&amp;url=http://silverghost.dyndns.org/wfrp/" /></a></p>

<p><strong>Liber Fanatica</strong><br />
<a border="0" href="http://www.liberfanatica.net/"><img alt="Generated by WebThumbnail.org" src="http://api.webthumbnail.org?width=200&amp;height=200&amp;screen=1024&amp;url=http://www.liberfanatica.net/" /></a></p>

<p><strong>Google + : WFRP 2E Refugees</strong><br />
<a border="0" href="https://plus.google.com/u/0/communities/109170996983631221869"><img alt="Generated by WebThumbnail.org" src="http://api.webthumbnail.org?width=200&amp;height=200&amp;screen=1024&amp;url=https://plus.google.com/u/0/communities/109170996983631221869" /></a></p>

<p><strong>Charles&#39; WFRP - Lots of articles and WFRP goodness</strong><br />
<a border="0" href="http://domokun.free.fr/wfrp"><img alt="Generated by WebThumbnail.org" src="http://api.webthumbnail.org?width=200&amp;height=200&amp;screen=1024&amp;url=http://domokun.free.fr/wfrp" /></a></p>

<p>&nbsp;</p>

<p>&nbsp;</p>
',
    'resized_imgs' => 
    array (
    ),
    'modified' => 1411088316,
    'modified_by' => 'Snotling',
  ),
);

