<?php

echo "Welcome to WH-NPC.  
      <p>WH-NPC is a Warhammer NPC (or player)Character Generator.  This program follows the rules in the Warhammer Fantasy Role Play Rule Book. <p>"
  . "<form method=POST action=generate.php> "
  . "<table border=0><tr>"
  . "<th valign=top align=right>Must Select:</th>"
  . "<td align=right valign=top>"
  . "Class: <select name=\"Class\"> "
  . "<option> Warrior "
  . "<option> Ranger "
  . "<option> Rogue "
  . "<option> Academic "
  . "</select> <br> "
  . "Race: <select name=\"Race\"> "
  . "<option> Human "
  . "<option> Elf "
  . "<option> Dwarf "
  . "<option> Halfling "
  . "</select> <br> "
  . "</td><th rowspan=2><img height=180 width=280 src=wfrplogo.gif></th></tr>"
  . "<th valign=top align=right>Optional:</th>"
  . "<td align=right valign=top>"
  . "Age: <select name=\"Age\"> "
  . "<option>Random "
  . "<option>Young "
  . "<option>Old "
  . "</select> <br> "
  . "Sex : <select name=\"Sex\"> "
  . "<option>Random "
  . "<option>Male "
  . "<option>Female "
  . "</select> <br> "
  . "</td></tr>"
  . "<th colspan=2>Press submit to Continue</th><td>"
  . "<input type=submit>"
  . "</td></tr>"
  . "</table>"
  . "</form>"
  . "<p>"
  . "<p>"
  . "<center><font size=2>Created by wh-npc v1.0</font>"
  . "<br>"
  . "<font size=-2>Warhammer and other Warhammer Fantasy Rople Play (and the Logo's) are (probably registered) trademarks of Games Workshop and/or HogsHead.  The use of trademarks and materials are not meant as a challange to their rights and is not intended to make or lose any money for anyone. "
  . "</font></center>"
//  . "To see what is new in the next version, select this <a href=nextversion.html>link</a>."
 ."";


?>
